import type { Ingredient } from '@/types';

export const ingredients: Ingredient[] = [
  {
    _id: '60666c42cc7b410027a1a9b1',
    name: 'Краторная булка N-200i',
    type: 'bun',
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    image: 'https://code.s3.yandex.net/react/code/bun-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b5',
    name: 'Говяжий метеорит (отбивная)',
    type: 'main',
    proteins: 800,
    fat: 800,
    carbohydrates: 400,
    calories: 2674,
    price: 3000,
    image: 'https://code.s3.yandex.net/react/code/meat-03.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b3',
    name: 'Филе Люминольного миньона',
    type: 'main',
    proteins: 44,
    fat: 26,
    carbohydrates: 5,
    calories: 643,
    price: 1200,
    image: 'https://code.s3.yandex.net/react/code/meat-01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-01-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b4',
    name: 'Биокотлета из марсианской Магнолии',
    type: 'main',
    proteins: 420,
    fat: 142,
    carbohydrates: 242,
    calories: 4242,
    price: 4242,
    image: 'https://code.s3.yandex.net/react/code/meat-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b6',
    name: 'Соус традиционный галактический',
    type: 'sauce',
    proteins: 10,
    fat: 100,
    carbohydrates: 10,
    calories: 99,
    price: 15,
    image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b7',
    name: 'Соус фирменный Space Sauce',
    type: 'sauce',
    proteins: 50,
    fat: 80,
    carbohydrates: 20,
    calories: 110,
    price: 80,
    image: 'https://code.s3.yandex.net/react/code/sauce-01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b8',
    name: 'Хрустящие минеральные кольца',
    type: 'main',
    proteins: 10,
    fat: 5,
    carbohydrates: 20,
    calories: 100,
    price: 300,
    image: 'https://code.s3.yandex.net/react/code/crystal.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/crystal-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/crystal-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9b9',
    name: 'Соус с шипами Антарианского пламени',
    type: 'sauce',
    proteins: 0,
    fat: 30,
    carbohydrates: 20,
    calories: 40,
    price: 30,
    image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9ba',
    name: 'Плоды Фалленианского дерева',
    type: 'main',
    proteins: 10,
    fat: 2,
    carbohydrates: 20,
    calories: 100,
    price: 880,
    image: 'https://code.s3.yandex.net/react/code/sp_01.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/sp_01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sp_01-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9bb',
    name: 'Кристаллы марсианских альфа-савок',
    type: 'main',
    proteins: 10,
    fat: 10,
    carbohydrates: 20,
    calories: 100,
    price: 200,
    image: 'https://code.s3.yandex.net/react/code/crystal-1.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/crystal-1-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/crystal-1-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9bc',
    name: 'Мини-салат Экзо-плантаго',
    type: 'main',
    proteins: 10,
    fat: 2,
    carbohydrates: 10,
    calories: 60,
    price: 150,
    image: 'https://code.s3.yandex.net/react/code/salad.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9bd',
    name: 'Салат Стелла',
    type: 'main',
    proteins: 80,
    fat: 10,
    carbohydrates: 10,
    calories: 420,
    price: 800,
    image: 'https://code.s3.yandex.net/react/code/salad-1.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/salad-1-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/salad-1-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9be',
    name: 'Хрустящие картофельные звезды',
    type: 'main',
    proteins: 10,
    fat: 0,
    carbohydrates: 20,
    calories: 100,
    price: 200,
    image: 'https://code.s3.yandex.net/react/code/french-fries.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/french-fries-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/french-fries-large.png',
    __v: 0,
  },
  {
    _id: '60666c42cc7b410027a1a9bf',
    name: 'Краторная булка N-200i',
    type: 'bun',
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    image: 'https://code.s3.yandex.net/react/code/bun-02.png',
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
    __v: 0,
  },
];
